repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^docs/source/(demos|tutorials)$
      - id: end-of-file-fixer
        exclude: ^docs/source/(demos|tutorials)$
      - id: check-yaml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.1
    hooks:
      - id: ruff-check
        args: ['--fix']
      - id: ruff-format

  - repo: https://github.com/mwouts/jupytext
    rev: v1.19.1
    hooks:
      - id: jupytext
        args: ['--from', 'ipynb', '--to', 'py:percent']
        files: ^(examples/|tutorials/)
        types: [jupyter]
